repos:
  - repo: https://github.com/pycqa/pylint
    rev: v3.3.1
    hooks:
    - id: pylint
      args:
      - -d import-error
      - -d duplicate-code
      - -d too-many-positional-arguments
  - repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
    - id: black
      language_version: python3
